// <auto-generated />
using System;
using ASP__Music_Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP__Music_Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230726205703_newList")]
    partial class newList
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("MusicServer")
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ASP__Music_Server.Data.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Avatar")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeleteDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Login")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RegsterDt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users", "MusicServer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fa2c02a0-a639-4c4f-8b96-b81946117d54"),
                            Email = "maksim24du@gmail.com",
                            Login = "Admin",
                            Name = "Root Administrator",
                            PasswordHash = "A826F31FEA8407572E533E55E9247B2BC348D372",
                            RegsterDt = new DateTime(2023, 7, 26, 23, 57, 3, 779, DateTimeKind.Local).AddTicks(9077)
                        });
                });

            modelBuilder.Entity("ASP__Music_Server.Models.Data.Entity.Music", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Executor")
                        .HasColumnType("longtext");

                    b.Property<float?>("GPA")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Path")
                        .HasColumnType("longtext");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("id_User")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.ToTable("Musics", "MusicServer");
                });

            modelBuilder.Entity("ASP__Music_Server.Models.Data.Entity.UserMusic", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MusicId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.ToTable("UserMusics", "MusicServer");
                });
#pragma warning restore 612, 618
        }
    }
}
